[apply]
command:/usr/local/opnsense/scripts/OPNsense/Suricata2Cuckoo/apply.php
parameters:
type:script_output
message:suricata2cuckoo apply

[restart]
command:/usr/local/etc/rc.d/suricata2cuckoo
parameters:restart
type:script_output
message:suricata2cuckoo restart
allowed_groups:wheel

[status]
command:/usr/local/etc/rc.d/suricata2cuckoo
parameters:status
type:script_output
errors:no
message:suricata2cuckoo status
allowed_groups:wheel
